# Generated by Django 5.1.4 on 2026-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee'), ('GHS', 'Ghanaian Cedi'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('AED', 'UAE Dirham'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso')], default='USD', max_length=3),
        ),
    ]
